# Generated by Django 3.2 on 2021-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='backgraund',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('PL', 'Polska'), ('ENG', 'England'), ('N', 'Nieokreślone')], default='N', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('N', 'Nieokreślone')], default='N', max_length=1),
        ),
    ]
