# Generated by Django 3.2 on 2021-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='privacy',
            field=models.CharField(choices=[('Pv', 'Private'), ('Pb', 'Public'), ('Fs', 'For Subscribents')], default='Pb', max_length=2),
        ),
    ]
