# Generated by Django 3.2 on 2021-05-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='backgraund',
            new_name='background',
        ),
    ]
