# Generated by Django 3.2 on 2021-04-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Jakis opis'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='nickname', max_length=20),
        ),
    ]
