# Generated by Django 3.2 on 2021-05-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20210504_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.Tags'),
        ),
    ]
