# Generated by Django 3.2 on 2021-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210504_1959'),
        ('videos', '0009_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='author',
        ),
        migrations.AddField(
            model_name='playlist',
            name='saved_on',
            field=models.ManyToManyField(blank=True, to='profiles.Profile'),
        ),
    ]
