# Generated by Django 3.2 on 2021-05-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210504_1959'),
        ('videos', '0010_auto_20210505_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='saved_on',
        ),
        migrations.AddField(
            model_name='playlist',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
