# Generated by Django 3.2 on 2021-05-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_alter_playlist_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='access',
            field=models.CharField(choices=[('S', 'System'), ('U', 'User')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='playlist',
            name='privacy',
            field=models.CharField(choices=[('Pv', 'Private'), ('Pb', 'Public'), ('Fs', 'For Subscribers')], default='Pb', max_length=2),
        ),
        migrations.AddField(
            model_name='playlist',
            name='tags',
            field=models.ManyToManyField(blank=True, to='videos.Tag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
