# Generated by Django 3.2 on 2021-05-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20210511_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='titile',
        ),
        migrations.AddField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
