# Generated by Django 3.2 on 2021-05-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_alter_playlist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
